# comment_width = 100
# format_code_in_doc_comments = true
# imports_granularity = "Module"
# match_arm_blocks = false
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
# wrap_comments = true
