pub const PARSER_MINIMAL_AST_CAPACITY: usize = 100_000;
pub const PARSER_MINIMAL_GLOBAL_CAPACITY: usize = 100_000;
pub const PARSER_MAX_ERRORS: usize = 50;

pub const PARSER_SYMBOLS_MINIMAL_GLOBAL_CAPACITY: usize = 100_000;
pub const PARSER_SYMBOLS_MINIMAL_LOCAL_CAPACITY: usize = 255;

pub const PARSER_STANDARD_ENTRYPOINT_MAIN_NAME: &[u8] = &[109, 97, 105, 110];
