pub const PARSER_MINIMAL_AST_CAPACITY: usize = 100_000;
pub const PARSER_MINIMAL_GLOBAL_CAPACITY: usize = 100_000;
pub const PARSER_MAX_ERRORS: usize = 50;

pub const PARSER_SYMBOLS_MINIMAL_GLOBAL_CAPACITY: usize = 100_000;
pub const PARSER_SYMBOLS_MINIMAL_LOCAL_CAPACITY: usize = 255;
