pub const LLVM_COMPILER_SYMBOLS_GLOBAL_MINIMAL_CAPACITY: usize = 100_000;
pub const LLVM_COMPILER_SYMBOLS_LOCAL_MINIMAL_CAPACITY: usize = 256;

pub const LLVM_COMPILER_BRANCHERS_CAPACITY: usize = 256;
