use crate::frontends::classical::lexer::tokentype::TokenType;

impl std::fmt::Display for TokenType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            // Keywords
            TokenType::And => write!(f, "and"),
            TokenType::Break => write!(f, "break"),
            TokenType::Const => write!(f, "const"),
            TokenType::Continue => write!(f, "continue"),
            TokenType::Elif => write!(f, "elif"),
            TokenType::Else => write!(f, "else"),
            TokenType::Enum => write!(f, "enum"),
            TokenType::False => write!(f, "false"),
            TokenType::Fn => write!(f, "fn"),
            TokenType::For => write!(f, "for"),
            TokenType::If => write!(f, "if"),
            TokenType::Loop => write!(f, "loop"),
            TokenType::Mut => write!(f, "mut"),
            TokenType::New => write!(f, "new"),
            TokenType::Or => write!(f, "or"),
            TokenType::Return => write!(f, "return"),
            TokenType::Struct => write!(f, "struct"),
            TokenType::True => write!(f, "true"),
            TokenType::Type => write!(f, "type"),
            TokenType::While => write!(f, "while"),
            TokenType::Write => write!(f, "write"),
            TokenType::Local => write!(f, "local"),
            TokenType::Asm => write!(f, "asm"),
            TokenType::GlobalAsm => write!(f, "global_asm"),

            // Indirect Call
            TokenType::Indirect => write!(f, "indirect"),

            // Types
            TokenType::Address => write!(f, "address"),
            TokenType::Bool => write!(f, "bool"),
            TokenType::Char => write!(f, "char"),
            TokenType::F32 => write!(f, "f32"),
            TokenType::F64 => write!(f, "f64"),
            TokenType::FX8680 => write!(f, "fx86_80"),
            TokenType::F128 => write!(f, "f128"),
            TokenType::FPPC128 => write!(f, "fppc_128"),
            TokenType::Ptr => write!(f, "ptr"),
            TokenType::Array => write!(f, "array"),
            TokenType::S8 => write!(f, "s8"),
            TokenType::S16 => write!(f, "s16"),
            TokenType::S32 => write!(f, "s32"),
            TokenType::S64 => write!(f, "s64"),
            TokenType::Str => write!(f, "const ptr[array[char]]"),
            TokenType::U8 => write!(f, "u8"),
            TokenType::U16 => write!(f, "u16"),
            TokenType::U32 => write!(f, "u32"),
            TokenType::U64 => write!(f, "u64"),
            TokenType::U128 => write!(f, "u128"),
            TokenType::FnRef => write!(f, "Fn"),
            TokenType::Void => write!(f, "void"),

            // Special
            TokenType::Unreachable => write!(f, "unreachable"),

            // Modificators
            TokenType::LazyThread => write!(f, "lazythread"),
            TokenType::Volatile => write!(f, "volatile"),

            TokenType::AtomNone => write!(f, "atomnone"),
            TokenType::AtomFree => write!(f, "atomfree"),
            TokenType::AtomRelax => write!(f, "atomrelax"),
            TokenType::AtomGrab => write!(f, "atomgrab"),
            TokenType::AtomDrop => write!(f, "atomdrop"),
            TokenType::AtomSync => write!(f, "atomsync"),
            TokenType::AtomStrict => write!(f, "atomstrict"),

            TokenType::ThreadDynamic => write!(f, "threaddyn"),
            TokenType::ThreadExec => write!(f, "threadexec"),
            TokenType::ThreadInit => write!(f, "threadinit"),

            // Attributes
            TokenType::OptFuzzing => write!(f, "@optfuzzing"),
            TokenType::NoUnwind => write!(f, "@nounwind"),
            TokenType::Packed => write!(f, "@packed"),
            TokenType::Stack => write!(f, "@stack"),
            TokenType::Static => write!(f, "@static"),
            TokenType::Heap => write!(f, "@heap"),
            TokenType::AlwaysInline => write!(f, "@alwaysinline"),
            TokenType::AsmAlignStack => write!(f, "@asmalignstack"),
            TokenType::AsmSyntax => write!(f, "@asmsyntax"),
            TokenType::AsmSideEffects => write!(f, "@asmeffects"),
            TokenType::AsmThrow => write!(f, "@asmthrow"),
            TokenType::Convention => write!(f, "@convention"),
            TokenType::Extern => write!(f, "@extern"),
            TokenType::Hot => write!(f, "@hot"),
            TokenType::Ignore => write!(f, "@ignore"),
            TokenType::Import => write!(f, "@import"),
            TokenType::InlineHint => write!(f, "@inlinehint"),
            TokenType::MinSize => write!(f, "@minsize"),
            TokenType::NoInline => write!(f, "@noinline"),
            TokenType::PreciseFloats => write!(f, "@precisefloats"),
            TokenType::Public => write!(f, "@public"),
            TokenType::SafeStack => write!(f, "@safestack"),
            TokenType::StrongStack => write!(f, "@strongstack"),
            TokenType::WeakStack => write!(f, "@weakstack"),

            // Operators, Punctuation, and Special Constructs
            TokenType::Float => write!(f, "integer"),
            TokenType::Integer => write!(f, "float"),
            TokenType::Addr => write!(f, "addr"),
            TokenType::Alloc => write!(f, "alloc"),
            TokenType::Arith => write!(f, "%"),
            TokenType::Arrow => write!(f, "->"),
            TokenType::AsmFn => write!(f, "asmfn"),
            TokenType::Bang => write!(f, "!"),
            TokenType::BangEq => write!(f, "!="),
            TokenType::As => write!(f, "as"),
            TokenType::Colon => write!(f, ":"),
            TokenType::ColonColon => write!(f, "::"),
            TokenType::Comma => write!(f, ","),
            TokenType::Defer => write!(f, "defer"),
            TokenType::Dot => write!(f, "."),
            TokenType::Eof => write!(f, "EOF"),
            TokenType::Eq => write!(f, "="),
            TokenType::EqEq => write!(f, "=="),
            TokenType::Greater => write!(f, ">"),
            TokenType::GreaterEq => write!(f, ">="),
            TokenType::Identifier => write!(f, "identifier"),
            TokenType::Fixed => write!(f, "fixed"),
            TokenType::Instr => write!(f, "instr"),
            TokenType::LBrace => write!(f, "{{"),
            TokenType::LBracket => write!(f, "["),
            TokenType::Less => write!(f, "<"),
            TokenType::LessEq => write!(f, "<="),
            TokenType::Load => write!(f, "load"),
            TokenType::LParen => write!(f, "("),
            TokenType::LShift => write!(f, "<<"),
            TokenType::Minus => write!(f, "-"),
            TokenType::MinusEq => write!(f, "-="),
            TokenType::MinusMinus => write!(f, "--"),
            TokenType::NullPtr => write!(f, "nullptr"),
            TokenType::Pass => write!(f, "..."),
            TokenType::Plus => write!(f, "+"),
            TokenType::PlusEq => write!(f, "+="),
            TokenType::PlusPlus => write!(f, "++"),
            TokenType::Range => write!(f, ".."),
            TokenType::RBrace => write!(f, "}}"),
            TokenType::RBracket => write!(f, "]"),
            TokenType::RParen => write!(f, ")"),
            TokenType::RShift => write!(f, ">>"),
            TokenType::SemiColon => write!(f, ";"),
            TokenType::Slash => write!(f, "/"),
            TokenType::Xor => write!(f, "^"),
            TokenType::Not => write!(f, "~"),
            TokenType::Bor => write!(f, "|"),
            TokenType::BAnd => write!(f, "&"),
            TokenType::Star => write!(f, "*"),
            TokenType::SizeOf => write!(f, "sizeof"),

            // Builtins
            TokenType::Halloc => write!(f, "halloc"),
            TokenType::AlignOf => write!(f, "alignof"),
            TokenType::MemSet => write!(f, "memset"),
            TokenType::MemMove => write!(f, "memmove"),
            TokenType::MemCpy => write!(f, "memcpy"),
        }
    }
}
