name: Thrush Compiler (Windows x86_64)

on:
  push:
    tags:
      - 'thrushc-x86_64-windows-v*.*.*'

jobs:
  build-mlir-windows:
    runs-on: windows-2022

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Generating Unique ID
        shell: pwsh
        run: |
          $BASE_NAME = "${env:GITHUB_REF}" -replace '^refs/tags/',''
          $VERSION = "${BASE_NAME}" -replace '^thrushc-x86_64-windows-',''
          $BUILD_ID = "${BASE_NAME}-${env:GITHUB_RUN_ID}"

          echo "BUILD_ID=$BUILD_ID" >> $env:GITHUB_ENV
          echo "TAG_NAME=$VERSION" >> $env:GITHUB_ENV
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

          echo "Unique ID: $BUILD_ID"
          echo "Base name: $VERSION"

      - name: Cloning Thrush Compiler
        run: |
          git clone --depth 1 https://github.com/thrushlang/thrushc

      - name: Installing dependencies
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://sh.rustup.rs -OutFile rustup-init.sh
          ./rustup-init.sh -y
          $env:PATH += ";$env:USERPROFILE\.cargo\bin"

          winget install MSYS2.MSYS2
          $env:PATH += ";C:\msys64\usr\bin"

          # Install required MSYS2 packages
          pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-upx mingw-w64-x86_64-zlib mingw-w64-x86_64-binutils mingw-w64-x86_64-xz

          winget install Python.Python.3.11

      - name: Building Thrush Compiler
        shell: pwsh
        run: |
          cd thrushc/builder
          cargo run
          cd ../scripts
          .\build.ps1 release
        working-directory: .

      - name: Extract Changelog
        shell: pwsh
        run: |
          $CHANGELOG_FILE = "thrushc/changelogs/windows/${env:TAG_NAME}.md"
          if (Test-Path $CHANGELOG_FILE) {
            $CHANGELOG_CONTENT = Get-Content $CHANGELOG_FILE -Raw
            echo "CHANGELOG_CONTENT<<EOF" >> $env:GITHUB_ENV
            echo "$CHANGELOG_CONTENT" >> $env:GITHUB_ENV
            echo "EOF" >> $env:GITHUB_ENV
          } else {
            echo "Changelog file $CHANGELOG_FILE not found!"
            echo "CHANGELOG_CONTENT=Changelog not found for this version." >> $env:GITHUB_ENV
          }

      - name: Releasing Thrush Compiler
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          name: "${{ env.VERSION }}"
          body: |
            ${{ env.CHANGELOG_CONTENT }}
          files: |
            thrushc/dist/windows/thrushc.exe
          draft: false
