name: Thrush Compiler (Linux x86_64)

on:
  push:
    tags:
      - 'thrushc-x86_64-linux-v*.*.*'

jobs:
  build-mlir-linux:
    runs-on: ubuntu-2022

    permissions:
      contents: write
  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
    steps:
      - name: Generating Unique ID
        run: |
          BASE_NAME=$(echo "$GITHUB_REF" | sed 's|^refs/tags/||')
          VERSION=$(echo "$BASE_NAME" | sed 's|^thrushc-x86_64-linux-||')
          BUILD_ID="${BASE_NAME}-${GITHUB_RUN_ID}" 
          
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV

          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV

          echo "Unique ID: $BUILD_ID"
          echo "Base name: $VERSION"
    
      - name: Cloning Thrush Compiler
        run: |
          git clone --depth 1 https://github.com/thrushlang/thrushc

      - name: Installing dependencies
        run: |
          sudo apt-get install -y upx-ucl build-essential python3 libz-dev binutils xz-utils libgccjit-12-dev
          sudo apt-get remove -y llvm-16* clang-16*
          sudo rm -rf /usr/lib/llvm-16

          curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Building Thrush Compiler
        run: |
          cd builder
          cargo run
          cd ..
          cd scripts
          sh build.sh release
        working-directory: thrushc

      - name: Extract Changelog
        run: |
          CHANGELOG_FILE="thrushc/changelogs/linux/${TAG_NAME}.md"
          if [ -f "$CHANGELOG_FILE" ]; then
            echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
            cat "$CHANGELOG_FILE" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "Changelog file $CHANGELOG_FILE not found!"
            echo "CHANGELOG_CONTENT=Changelog not found for this version." >> $GITHUB_ENV
          fi

      - name: Releasing Thrush Compiler
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          name: "${{ env.VERSION }}"
          body: |
            ${{ env.CHANGELOG_CONTENT }}
          files: |
            thrushc/dist/linux/thrushc
            
          draft: false